### ISSUE TITLE
Use "system gray" for boot splash?

### ISSUE THREAD

**Issue by cassidyjames** [elementary/plymouth-theme#1]
We've aligned on a system gray color and texture for the login/lock screen and the "underneath" layer in Gala multitasking. Would it make sense to use this behind the logo for the boot splash as well? Is it even possible to get the texture in there? Reasoning:

- Consistency with the sort of under-the-hood system layer
- IPS displays tend to show worse light bleed on black backgrounds; notice Apple avoids an all-black screen during boot for this reason. ;)
- It feels a little less tech/nerdy to me, but that's pretty subjective

Arguments against/things to figure out:

- If we don't have flicker-free boot, a non-black screen would be more jarring than flickering from a blank black screen to a black screen with a logo.
- Pop!_OS completely removed a boot splash I believe, because it added more time to the boot process to show it. Maybe we look into doing that, too?

**Comment by meisenzahl** [comment]
Close in favor of https://github.com/elementary/os/issues/367
